apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: el77jlnqc-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: el77jlnqc-nodejs 
  name: el77jlnqc-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: el77jlnqc-nodejs 
